// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order_reserve.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isOrderReserved = `-- name: IsOrderReserved :one
SELECT EXISTS (
    SELECT 1 FROM order_reservations
    WHERE order_id = $1 AND reservation_status = 'RESERVED'
) AS reserved
`

func (q *Queries) IsOrderReserved(ctx context.Context, orderID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isOrderReserved, orderID)
	var reserved bool
	err := row.Scan(&reserved)
	return reserved, err
}
