// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetListProductsByShop(ctx context.Context, arg GetListProductsByShopParams) ([]Product, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
}

var _ Querier = (*Queries)(nil)
