version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: go-shop-redis
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis_data:/data
    networks:
      - go-shop-network

volumes:
  redis_data:

networks:
  go-shop-network:
    driver: bridge