version: '3.8'

services:
  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_VOLUME_NAME:-redis_data}:/data
    networks:
      - go-shop-network

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:15-alpine}
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-go_shop}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS:---encoding=UTF-8 --lc-collate=C --lc-ctype=C}
    volumes:
      - ${POSTGRES_VOLUME_NAME:-postgres_data}:/var/lib/postgresql/data
      - ${POSTGRES_INIT_VOLUME:-./init}:/docker-entrypoint-initdb.d
    networks:
      - go-shop-network


volumes:
  redis_data:
    name: ${REDIS_VOLUME_NAME:-redis_data}
  postgres_data:
    name: ${POSTGRES_VOLUME_NAME:-postgres_data}

networks:
  go-shop-network:
    name: ${NETWORK_NAME:-go-shop-network}
    driver: bridge