version: '3.8'

services:
  # Microservices
  user-service:
    build:
      context: ../internal/services/user-service
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME:-go-shop}-user-service
    ports:
      - "${USER_SERVICE_PORT:-8080}:8080"
    env_file:
      - .env
      - ./internal/services/user-service/.env
    depends_on:
      - postgres-user-service
      - redis-cache
    networks:
      - go-shop-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres-user-service:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME:-go-shop}-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
      - ./internal/services/user-service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - go-shop-network
    restart: unless-stopped

  # Infrastructure services
  redis-cache:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    container_name: ${PROJECT_NAME:-go-shop}-redis-cache
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - ${REDIS_VOLUME_NAME:-redis_data}:/data
    networks:
      - go-shop-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  go-shop-network:
    driver: bridge