app:
  name: "go-shop-cart-service"
  version: "1.0.0"
  environment: "development"
  log_level: "info"

server:
  host: "0.0.0.0"
  port: "8083"
  read_timeout: "10s"
  write_timeout: "10s"

database:
  host: "localhost"
  port: "6003"
  user: "postgres"
  password: "toai20102002" 
  name: "cart_service_go_shop_db"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 1 
