// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentOutboxEvent, error)
	GetBatchPaymentEventsByEventTypeAndStatus(ctx context.Context, arg GetBatchPaymentEventsByEventTypeAndStatusParams) ([]PaymentOutboxEvent, error)
	GetPaymentByOrderID(ctx context.Context, orderID pgtype.UUID) (Payment, error)
	UpdatePaymentEvent(ctx context.Context, arg UpdatePaymentEventParams) (PaymentOutboxEvent, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
