# monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-microservices'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Giữ lại container có label prometheus.scrape=true
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      # Đặt tên job từ tên service trong docker-compose
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: job
      # Đặt địa chỉ scrape là <IP_container>:9100 cho tất cả
      - source_labels: [__meta_docker_container_network_ip]
        target_label: __address__
        replacement: "${1}:9100"

  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong-gateway:8001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']