# monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-microservices'
    static_configs:
      - targets: 
          - 'cart-service:9100'
          - 'order-service:9100'
          - 'product-service:9100'
          - 'shop-service:9100'
          - 'user-service:9100'

  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong-gateway:8001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']