# monitoring/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
    # Chỉ giữ container có label prometheus.scrape=true
    - source_labels: [__meta_docker_container_label_prometheus_scrape]
      action: keep
      regex: true
    # Đặt tên job bằng tên service trong docker-compose
    - source_labels: [__meta_docker_container_label_com_docker_compose_service]
      target_label: job
    # Lấy IP container và gán port từ label prometheus.port
    - source_labels: [__meta_docker_container_network_ip, __meta_docker_container_label_prometheus_port]
      target_label: __address__
      regex: (.*);(.*)
      replacement: $1:$2
    - source_labels: [__meta_docker_container_state]
      action: keep
      regex: running

  - job_name: 'go-microservices'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong-gateway:8001']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']