version: '3.8'

services:
  redis:
    # Override base config for development
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-redis-dev
    command: redis-server --loglevel ${REDIS_LOG_LEVEL:-verbose} --save ${REDIS_SAVE_INTERVAL:-60 1}
    environment:
      - REDIS_LOG_LEVEL=${REDIS_LOG_LEVEL:-debug}
      - REDIS_ENV=${APP_ENV:-development}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_VOLUME_NAME:-redis_dev_data}:/data
    networks:
      - go-shop-network
      
  # Additional service for development only
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-redis-commander
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
    depends_on:
      - redis
    networks:
      - go-shop-network

volumes:
  redis_dev_data:
    name: ${REDIS_VOLUME_NAME:-redis_dev_data}