version: '3.8'

services:
  # Override service configurations for development
  user-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
      - DB_NAME=go_shop_user_service_dev
    env_file:
      - ../../internal/services/user-service/.env
    volumes:
      - ../../internal/services/user-service:/app
    command: go run cmd/main.go

  shop-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
      - DB_NAME=go_shop_shop_service_dev
    env_file:
      - ../../internal/services/shop-service/.env
    volumes:
      - ../../internal/services/shop-service:/app
    command: go run cmd/main.go

  order-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
      - DB_NAME=go_shop_order_service_dev
    env_file:
      - ../../internal/services/order-service/.env
    volumes:
      - ../../internal/services/order-service:/app
    command: go run cmd/main.go

  payment-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
      - DB_NAME=go_shop_payment_service_dev
    env_file:
      - ../../internal/services/payment-service/.env
    volumes:
      - ../../internal/services/payment-service:/app
    command: go run cmd/main.go

  shipping-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
      - DB_NAME=go_shop_shipping_service_dev
    env_file:
      - ../../internal/services/shipping-service/.env
    volumes:
      - ../../internal/services/shipping-service:/app
    command: go run cmd/main.go

  review-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
      - DB_NAME=go_shop_review_service_dev
    env_file:
      - ../../internal/services/review-service/.env
    volumes:
      - ../../internal/services/review-service:/app
    command: go run cmd/main.go

  notification-service:
    environment:
      - SERVICE_ENV=development
      - LOG_LEVEL=debug
    env_file:
      - ../../internal/services/notification-service/.env
    volumes:
      - ../../internal/services/notification-service:/app
    command: go run cmd/main.go
  redis:
    # Override base config for development
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-redis-dev
    command: redis-server --loglevel ${REDIS_LOG_LEVEL:-verbose} --save ${REDIS_SAVE_INTERVAL:-60 1}
    environment:
      - REDIS_LOG_LEVEL=${REDIS_LOG_LEVEL:-debug}
      - REDIS_ENV=${APP_ENV:-development}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ${REDIS_VOLUME_NAME:-redis_dev_data}:/data
    networks:
      - go-shop-network

  postgres:
    # Override base config for development
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-postgres-dev
    environment:
      - POSTGRES_DB=${DB_NAME:-go_shop_dev}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-dev_password}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS:---encoding=UTF-8 --lc-collate=C --lc-ctype=C}
    volumes:
      - ${POSTGRES_VOLUME_NAME:-postgres_dev_data}:/var/lib/postgresql/data
    networks:
      - go-shop-network
      
  # Additional service for development only
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-redis-commander
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
    depends_on:
      - redis
    networks:
      - go-shop-network

  # PostgreSQL Admin UI for development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-pgadmin
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@go-shop.dev
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    depends_on:
      - postgres
    networks:
      - go-shop-network

volumes:
  redis_dev_data:
    name: ${REDIS_VOLUME_NAME:-redis_dev_data}
  postgres_dev_data:
    name: ${POSTGRES_VOLUME_NAME:-postgres_dev_data}