// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders 
(
    id,
    user_id,
    shop_id,
    shipping_address_id,
    promotion_id,
    order_status
)
VALUES 
(
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, shop_id, shipping_address_id, promotion_id, order_status, created_at, updated_at
`

type CreateOrderParams struct {
	ID                pgtype.UUID `json:"id"`
	UserID            pgtype.UUID `json:"user_id"`
	ShopID            pgtype.UUID `json:"shop_id"`
	ShippingAddressID pgtype.UUID `json:"shipping_address_id"`
	PromotionID       pgtype.UUID `json:"promotion_id"`
	OrderStatus       OrderStatus `json:"order_status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.ShopID,
		arg.ShippingAddressID,
		arg.PromotionID,
		arg.OrderStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.ShippingAddressID,
		&i.PromotionID,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, shop_id, shipping_address_id, promotion_id, order_status, created_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopID,
		&i.ShippingAddressID,
		&i.PromotionID,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, user_id, shop_id, shipping_address_id, promotion_id, order_status, created_at, updated_at FROM orders
WHERE user_id = $1
`

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShopID,
			&i.ShippingAddressID,
			&i.PromotionID,
			&i.OrderStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
