// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders 
(
    id,
    owner_id,
    shop_id,
    shipping_address_id,
    promotion_id,
    shipping_fee,
    discount_amount,
    total_amount,
    final_amount,
    order_status
)
VALUES 
(
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, owner_id, shop_id, shipping_address_id, promotion_id, shipping_fee, discount_amount, total_amount, final_amount, order_status, created_at, updated_at
`

type CreateOrderParams struct {
	ID                pgtype.UUID    `json:"id"`
	OwnerID           pgtype.UUID    `json:"owner_id"`
	ShopID            pgtype.UUID    `json:"shop_id"`
	ShippingAddressID pgtype.UUID    `json:"shipping_address_id"`
	PromotionID       pgtype.UUID    `json:"promotion_id"`
	ShippingFee       pgtype.Numeric `json:"shipping_fee"`
	DiscountAmount    pgtype.Numeric `json:"discount_amount"`
	TotalAmount       pgtype.Numeric `json:"total_amount"`
	FinalAmount       pgtype.Numeric `json:"final_amount"`
	OrderStatus       OrderStatus    `json:"order_status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OwnerID,
		arg.ShopID,
		arg.ShippingAddressID,
		arg.PromotionID,
		arg.ShippingFee,
		arg.DiscountAmount,
		arg.TotalAmount,
		arg.FinalAmount,
		arg.OrderStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ShopID,
		&i.ShippingAddressID,
		&i.PromotionID,
		&i.ShippingFee,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.FinalAmount,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, owner_id, shop_id, shipping_address_id, promotion_id, shipping_fee, discount_amount, total_amount, final_amount, order_status, created_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ShopID,
		&i.ShippingAddressID,
		&i.PromotionID,
		&i.ShippingFee,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.FinalAmount,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, owner_id, shop_id, shipping_address_id, promotion_id, shipping_fee, discount_amount, total_amount, final_amount, order_status, created_at, updated_at FROM orders
WHERE owner_id = $1
`

func (q *Queries) GetOrdersByUserID(ctx context.Context, ownerID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ShopID,
			&i.ShippingAddressID,
			&i.PromotionID,
			&i.ShippingFee,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.FinalAmount,
			&i.OrderStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleOrders = `-- name: GetStaleOrders :many
SELECT id, owner_id, shop_id, shipping_address_id, promotion_id, shipping_fee, discount_amount, total_amount, final_amount, order_status, created_at, updated_at FROM orders 
WHERE order_status = 'PENDING'
AND updated_at < $1
LIMIT $2
`

type GetStaleOrdersParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) GetStaleOrders(ctx context.Context, arg GetStaleOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getStaleOrders, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ShopID,
			&i.ShippingAddressID,
			&i.PromotionID,
			&i.ShippingFee,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.FinalAmount,
			&i.OrderStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET order_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, shop_id, shipping_address_id, promotion_id, shipping_fee, discount_amount, total_amount, final_amount, order_status, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	OrderStatus OrderStatus `json:"order_status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.OrderStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ShopID,
		&i.ShippingAddressID,
		&i.PromotionID,
		&i.ShippingFee,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.FinalAmount,
		&i.OrderStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
