// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrdersByUserID(ctx context.Context, ownerID pgtype.UUID) ([]Order, error)
	GetStaleOrders(ctx context.Context, arg GetStaleOrdersParams) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
