// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
}

var _ Querier = (*Queries)(nil)
