// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (ShopPromotion, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	CreateShopAddress(ctx context.Context, arg CreateShopAddressParams) (pgtype.UUID, error)
	DeletePromotion(ctx context.Context, id pgtype.UUID) error
	DeleteShop(ctx context.Context, id pgtype.UUID) error
	GetAllPromotionsByStatus(ctx context.Context, promotionStatus NullPromotionStatus) ([]ShopPromotion, error)
	GetPromotionByID(ctx context.Context, id pgtype.UUID) (ShopPromotion, error)
	GetPromotionsByShopID(ctx context.Context, shopID pgtype.UUID) ([]ShopPromotion, error)
	GetShopByID(ctx context.Context, id pgtype.UUID) (Shop, error)
	GetShopsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Shop, error)
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) (ShopPromotion, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
}

var _ Querier = (*Queries)(nil)
