// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	DeleteShop(ctx context.Context, id pgtype.UUID) error
	GetShopByID(ctx context.Context, id pgtype.UUID) (Shop, error)
	GetShopsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Shop, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
}

var _ Querier = (*Queries)(nil)
