// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	IsDefault pgtype.Bool        `json:"is_default"`
	Street    string             `json:"street"`
	Ward      pgtype.Text        `json:"ward"`
	District  pgtype.Text        `json:"district"`
	City      pgtype.Text        `json:"city"`
	Country   pgtype.Text        `json:"country"`
	Lat       pgtype.Float8      `json:"lat"`
	Long      pgtype.Float8      `json:"long"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShipperProfile struct {
	UserID          pgtype.UUID `json:"user_id"`
	VehicleType     pgtype.Text `json:"vehicle_type"`
	VehicleImageUrl pgtype.Text `json:"vehicle_image_url"`
	IdentifyCardUrl pgtype.Text `json:"identify_card_url"`
	LicensePlate    pgtype.Text `json:"license_plate"`
	Status          string      `json:"status"`
}

type UserAccount struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	UserRole       string             `json:"user_role"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type UserProfile struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Email            string             `json:"email"`
	FullName         pgtype.Text        `json:"full_name"`
	Birthday         pgtype.Date        `json:"birthday"`
	Phone            pgtype.Text        `json:"phone"`
	Role             pgtype.Text        `json:"role"`
	BannedAt         pgtype.Timestamptz `json:"banned_at"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Gender           pgtype.Text        `json:"gender"`
	DefaultAddressID pgtype.UUID        `json:"default_address_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
