version: '3.8'

services:
  redis:
    # Override base config for production
    container_name: ${COMPOSE_PROJECT_NAME:-go-shop}-redis-prod
    command: redis-server --appendonly yes --maxmemory ${REDIS_MAX_MEMORY:-1gb} --maxmemory-policy ${REDIS_MAX_MEMORY_POLICY:-allkeys-lru} --save ${REDIS_SAVE_CONFIG:-900 1 300 10 60 10000}
    restart: unless-stopped
    environment:
      - REDIS_ENV=${APP_ENV:-production}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: ${REDIS_HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${REDIS_HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${REDIS_HEALTH_CHECK_RETRIES:-3}
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: ${REDIS_MEMORY_LIMIT:-1G}
          cpus: '${REDIS_CPU_LIMIT:-1.0}'
        reservations:
          memory: ${REDIS_MEMORY_RESERVATION:-512M}
          cpus: '${REDIS_CPU_RESERVATION:-0.5}'
    volumes:
      - ${REDIS_VOLUME_NAME:-redis_prod_data}:/data
    networks:
      - go-shop-network
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILE:-3}"

volumes:
  redis_prod_data:
    name: ${REDIS_VOLUME_NAME:-redis_prod_data}
    driver: local