// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error)
	CreateCart(ctx context.Context, ownerID pgtype.UUID) (Cart, error)
	DeleteCart(ctx context.Context, ownerID pgtype.UUID) error
	DeleteItemFromCart(ctx context.Context, id pgtype.UUID) error
	GetCartByOwnerID(ctx context.Context, ownerID pgtype.UUID) (Cart, error)
	GetItemsByCartID(ctx context.Context, cartID pgtype.UUID) ([]CartItem, error)
	UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (CartItem, error)
	UpsertCart(ctx context.Context, arg UpsertCartParams) (Cart, error)
	UpsertItemInCart(ctx context.Context, arg UpsertItemInCartParams) (CartItem, error)
}

var _ Querier = (*Queries)(nil)
